version: 2
sources:
  - name: warehouse
    schema: main
    tables:
      - name: generation_raw
        identifier: entsoe_generation_raw

      - name: prices_raw
        identifier: entsoe_prices_raw