version: 2
sources:
  - name: warehouse
    schema: main
    tables:
      - name: generation_raw
        identifier: entsoe_generation_raw

      - name: prices_raw
        identifier: entsoe_prices_raw

      - name: ipi_raw
        identifier: scb_ipi_raw

      - name: fx_raw
        identifier: fx_rates_raw


  #- name: dagster
   # tables:
    #  - name: scb_ipi_raw